### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by Android-s14** [android10/frodo#5]
I've caught this stacktrace, please check if it's relevant:
```
     Caused by: java.lang.NullPointerException
            at android.util.Pair.hashCode(Pair.java:62)
            at java.lang.Object.toString(Object.java:332)
            at java.lang.String.valueOf(String.java:1681)
            at com.fernandocejas.frodo.internal.MessageBuilder.buildObservableOnNextMessage(MessageBuilder.java:92)
            at com.fernandocejas.frodo.internal.MessageManager.printObservableOnNext(MessageManager.java:34)
            at com.fernandocejas.frodo.internal.FrodoObservable$5.call(FrodoObservable.java:42)
            at rx.Observable$11.onNext(Observable.java:4417)
            at rx.internal.operators.OperatorDoOnEach$1.onNext(OperatorDoOnEach.java:79)
            at rx.observers.Subscribers$5.onNext(Subscribers.java:234)
            at rx.internal.operators.NotificationLite.accept(NotificationLite.java:150)
            at rx.internal.util.RxRingBuffer.accept(RxRingBuffer.java:443)
            at rx.internal.operators.OnSubscribeCombineLatest$MultiSourceProducer.tick(OnSubscribeCombineLatest.java:152)
            at rx.internal.operators.OnSubscribeCombineLatest$MultiSourceProducer.onNext(OnSubscribeCombineLatest.java:209)
            at rx.internal.operators.OnSubscribeCombineLatest$MultiSourceRequestableSubscriber.onNext(OnSubscribeCombineLatest.java:257)
            at rx.internal.operators.OperatorMerge$MergeSubscriber.emitScalar(OperatorMerge.java:472)
            at rx.internal.operators.OperatorMerge$MergeSubscriber.tryEmit(OperatorMerge.java:434)
            at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:227)
            at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:140)
            at rx.internal.operators.OnSubscribeFromIterable$IterableProducer.slowpath(OnSubscribeFromIterable.java:97)
            at rx.internal.operators.OnSubscribeFromIterable$IterableProducer.request(OnSubscribeFromIterable.java:73)
            at rx.Subscriber.setProducer(Subscriber.java:211)
            at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:49)
            at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:32)
            at rx.Observable$2.call(Observable.java:162)
            at rx.Observable$2.call(Observable.java:154)
            at rx.Observable.unsafeSubscribe(Observable.java:7710)
            at rx.internal.operators.OnSubscribeCombineLatest$MultiSourceProducer.request(OnSubscribeCombineLatest.java:131)
            at rx.Subscriber.setProducer(Subscriber.java:211)
            at rx.Subscriber.setProducer(Subscriber.java:205)
            at rx.Subscriber.setProducer(Subscriber.java:205)
            at rx.Subscriber.setProducer(Subscriber.java:205)
            at rx.Subscriber.setProducer(Subscriber.java:205)
            at rx.Subscriber.setProducer(Subscriber.java:205)
            at rx.Subscriber.setProducer(Subscriber.java:205)
            at rx.Subscriber.setProducer(Subscriber.java:205)
            at rx.internal.operators.OnSubscribeCombineLatest.call(OnSubscribeCombineLatest.java:68)
            at rx.internal.operators.OnSubscribeCombineLatest.call(OnSubscribeCombineLatest.java:45)
            at rx.Observable
```

**Comment by android10** [comment]
I will appreciate if you are more specific with what you are trying to do. 
Even better if you can put some code of your annotated method.

**Comment by Android-s14** [comment]
After looking at this stacktrace second time I realize it shows something strange: NPE when obtaining hashcode on `Pair` object. As for the context: I don't have the exact code right now, but it was `combineLatest` on two observables, plus perhaps some more operators downstream involving `Pair`s. Since I don't see how this stacktrace is even possible, the issue can be closed, if you don't have any other thoughts.

**Comment by android10** [comment]
Ok. I will close until we have more information or any other similar case.
